config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "chatroom#home"
  get "about/", to:"chatroom#about"

  get "signup/", to:"users#new"
  post "signup/", to:"users#create"

  get "login/", to:"sessions#new"
  post "login/", to:"sessions#create"
  get "logout/", to:"sessions#destroy"

  resources :users, only: [:index, :show, :edit, :update, :destroy]

  post "message/", to:"messages#create"
  # get "test/", to:"users#test"

  mount ActionCable.server, at:'/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates :body, presence:true
  
end

app/models/user.rb
class User < ApplicationRecord
	has_many :messages
	has_secure_password

	validates :username, :presence => true
	validates :username, :length => {
		in: 5..21
	}


	VALID_EMAIL_REGEX = /\a\z/
	validates :email, :presence => true, uniqueness: {case_sensitive:false}
	validates :password, :presence => true, length:{
		minimum:7
	}
	validates :password, :confirmation => true
	validates :password_confirmation, presence:true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
	private
	def login_required
		unless logged_in?
			store_location
			redirect_to login_path
		end
	end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
	before_action :login_required, 

	def home
		@message = Message.new
		@messages = Message.all
	end

	def about

	end
end

app/controllers/follow_controller.rb
class FollowController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def create
		@message = current_user.messages.new(message_param)
		if @message && @message.save
			# @messages = Message.all
			ActionCable.server.broadcast("chatroom_channel",{mod_message:render_message})
			# redirect_to root_path
		end
	end

	def render_message
		render(partial:'message',locals:{message:@message})
	end

	private
	def message_param
		params.require(:messages).permit(:body)
	end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.find_by(email: params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			login @user
			flash[:success] = "login successful"
			redirect_back_or root_path
		else
			flash.now[:danger] = "login failed, incorrect credential"
			render :new, status: :unprocessable_entity
		end
	end

	def destroy
		if current_user
			logout
			redirect_to root_path
		end
	end

	def session_params
		params.require(:sessions).permit(:email,:password)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
	end

	def show
	end

	def new
		@user = User.new
	end

	def create
		
		@user = User.new(user_param)
		if @user.save
			flash[:success] = "User #{@user.email} created successfully"
			redirect_to login_path
		else
			# flash[:alert] = "signup failed please try again"
			# puts @user.errors.full_messages
			# flash.now[:notice] = "flash errors"  status: :unprocessable_entity
			render :new, status: :unprocessable_entity
		end
	end

	def edit
	end

	def update
	end

	def destroy
	end

	def test
		flash.now[:notic] = "test"
		render :test
	end

	def user_param
		params.require(:user).permit(:username,:email,:password,:password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def login(user)
		session[:current_user_id] = user.id
		@current_user = user
	end

	def logout
		if session[:current_user_id]
			session.delete(:current_user_id)
			@current_user = nil
		end
	end

	def current_user
		if session[:current_user_id]
			@current_user ||= User.find(session[:current_user_id])
		else
			return nil
		end
	end

	def current_user?(user)
		@current_user == user
	end

	def logged_in?
		!current_user.nil?
	end

	def store_location
		session[:requested_url] = request.original_url if request.get?
	end

	def redirect_back_or(default)
		redirect_to(session[:requested_url]||default)
		session.delete(:requested_url)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatroom/about.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end %>

app/views/chatroom/home.html.erb
<%= stylesheet_link_tag "chatroom_welcome" %>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end %>
<div class="container mt-5">
  <div class="columns">
    <div class="column is-8">
      <div class="card chatbox">
        <div class="card-content">
            <div class="content box fit" id="message-container">
              <%= render @messages %>
            </div>
         </div>
         <footer class="card-footer down">
            <%= form_with(model:@message, scope: :messages, url:message_path,method: :post) do |f| %>
              <div class="is-inline-flex">
                <div class="field">
                  <div class="control">
                    <%= f.text_field :body, class: "input is-small is-rounded stretch", placeholder: "Enter message" %>
                  </div>
                </div>
                <div class="field">
                  <div class="control">
                    <button class="button is-info is-small ml-2 is-rounded">
                      <span class="icon is-small is-left">
                        <i class="mdi mdi-chat"></i>
                      </span>
                      <span>Send</span>
                    </button>
                  </div>
                </div>
              </div>
            <% end %>
        </footer>
      </div>
    </div>
    <div class="column is-4">
      <div class="card">
        <div class="card-content">
          <div class="content">
            Lorem ipsum leo risus, porta ac consectetur ac, vestibulum at eros. Donec id elit non mi porta gravida at eget metus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras mattis consectetur purus sit amet fermentum.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class:"navbar-item" do %>
      <h2 class="title has-text-white-bis">MessageAbes</h2>
    <% end %>
    <a role="button" class="navbar-burger" id="burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="nav-links" class="navbar-menu">
    <div class="navbar-start">
      <%=link_to "Chatroom", root_path, class:"navbar-item" %>
      <%= link_to "About", about_path, class:"navbar-item" %>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if current_user %>
            <%= link_to "#", class:"button is-info" do %>
              <strong><%= @current_user.username %></strong>
            <% end %>
            <%= link_to "Logout", logout_path, class: "button is-light" %>
          <% else %>
            <%= link_to signup_path, class:"button is-info" do %>
              <strong>Sign up</strong>
            <% end %>
            <%= link_to "Log in",login_path, class:"button is-light" %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageAbes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@6.5.95/css/materialdesignicons.min.css" /> 

  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= javascript_include_tag "chatroom_home" %>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </body>
</html>

app/views/messages/_message.html.erb
<article class="message is-small is-dark shadow">
  <div class="message-header">
    <%= link_to "#" do %>
      <p><%= message.user.email %> | <%= message.user.username %></p>
    <% end %>
  </div>
  <div class="message-body">
    <%= message.body %>
  </div>
</article>

app/views/users/new.html.erb
<%= stylesheet_link_tag "signup" %>
<div class="hero is-fullheight is-info">
	<div class="hero-body">
		<div class="container">
			<div class="columns is-centered">
				<div class="column is-5 box">
					<div class="has-text-centered">
						<h3 class="title has-text-grey-dark">SIGNUP</h3>
					</div>
					<hr>
					<div class=has-text-centered>
						<% flash.each do |type, msg| %>
						  <div class="error">
						    <%= msg %>
						  </div>
						<% end %>
					</div>
					<%= form_with(model: @user,url: signup_path, method: :post) do |f| %>
						<div class="field">
							<%= f.label :username, "Username", class: "label"%>
							<%@user.errors.full_messages_for(:username).each do |message| %>
								<div class="error">
									* <%=  message %>
								</div>
							<% end %>
							<div class="control has-icons-left">
								<%= f.text_field :username, class:"input" %>
								<span class="icon is-small is-left">
									<i class="fa fa-user"></i>
								</span>
							</div>	
						</div>
						<div class="field">
							<%= f.label :emal, "email", class: "label"%>
							<%@user.errors.full_messages_for(:email).each do |message| %>
								<div class="error">* <%= message %></div>
							<% end %>
							<div class="control has-icons-left">
								<%= f.email_field :email, class:"input" %>
								<span class="icon is-small is-left">
									<i class="fa fa-envelope"></i>
								</span>
							</div>	
						</div>
						<div class="field">
							<%= f.label :password, "Password", class: "label"%>
							<%@user.errors.full_messages_for(:password).each do |message| %>
								<div class="error">* <%= message %></div>
							<% end %>
							<div class="control has-icons-left">
								<%= f.password_field :password, class:"input" %>
								<span class="icon is-small is-left">
									<i class="fa fa-lock"></i>
								</span>
							</div>	
						</div>
						<div class="field">
							<%= f.label :password_confirmation, "Confirm Password", class: "label"%>
							<%@user.errors.full_messages_for(:password_confirmation).each do |message| %>
								<div class="error">* <%= message %></div>
							<% end %>
							<div class="control has-icons-left">
								<%= f.password_field :password_confirmation, class:"input" %>
								<span class="icon is-small is-left">
									<i class="fa fa-lock"></i>
								</span>
							</div>	
						</div>
						<div class="field">
							<div class="control">
								<%= f.submit "Signup", class:"button is-success is-fullwidth" %>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/test.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>